version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:2022.04.1
    resource_class: medium
    steps:
      - checkout
      - run: sudo apt-get install squashfs-tools
      - run:
          command: bash build.sh
          no_output_timeout: 30m

workflows:
  build-workflow:
    jobs:
      - build
