version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:2022.04.1
    resource_class: medium
    steps:
      - checkout
      - run: sudo apt-get install squashfs-tools
      - run: bash build.sh

workflows:
  build-workflow:
    jobs:
      - build
