version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: sudo apt-get install squashfs-tools
      - run: bash build.sh

workflows:
  build-workflow:
    jobs:
      - build
