version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:2022.04.1
    resource_class: large
    steps:
      - checkout
      - run: sudo apt-get install squashfs-tools
      - run:
          command: bash build.sh
          no_output_timeout: 40m
      - store_artifacts:
          path: smart-contract-sanctuary.sqsh

workflows:
  build-workflow:
    jobs:
      - build
