name: Build
on: [push]
concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        chain:
          - ethereum
          - polygon
    steps:
      - uses: actions/checkout@v3
        with:
          repository: tintinweb/smart-contract-sanctuary-${{ matrix.chain }}
          path: ${{ matrix.chain }}
      - name: Install squashfs-tools
        run: |
          sudo apt-get update
          sudo apt-get install squashfs-tools
      - name: Build squashfs filesystem
        run: |
          mksquashfs ${{ matrix.chain }} smart-contract-sanctuary.sqsh -comp lzo -no-strip -wildcards -e '... .git'
