name: Build
on: [push]
concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install squashfs-tools
        run: |
          sudo apt-get update
          sudo apt-get install squashfs-tools
      - uses: actions/checkout@v3
      - run: bash build.sh
      - uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: smart-contract-sanctuary.sqsh
